// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqJ1wShGzSxmfe9TOOSFL4ZCQelgW6KFY',
    appId: '1:356796506211:web:db2220ec6f6ad86a06d856',
    messagingSenderId: '356796506211',
    projectId: 'swinghop',
    authDomain: 'swinghop.firebaseapp.com',
    storageBucket: 'swinghop.firebasestorage.app',
    measurementId: 'G-CPTCBW2XVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2QAFusk3r1Q7t2FyB6HbEoQSvLM4imf4',
    appId: '1:356796506211:android:d7d64787c5e86ee306d856',
    messagingSenderId: '356796506211',
    projectId: 'swinghop',
    storageBucket: 'swinghop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd_a02YzTmYpiFQ7IfO8_-7_oG5MFR7KU',
    appId: '1:356796506211:ios:9cace33734a8174b06d856',
    messagingSenderId: '356796506211',
    projectId: 'swinghop',
    storageBucket: 'swinghop.firebasestorage.app',
    iosBundleId: 'com.example.swingHop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd_a02YzTmYpiFQ7IfO8_-7_oG5MFR7KU',
    appId: '1:356796506211:ios:9cace33734a8174b06d856',
    messagingSenderId: '356796506211',
    projectId: 'swinghop',
    storageBucket: 'swinghop.firebasestorage.app',
    iosBundleId: 'com.example.swingHop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqJ1wShGzSxmfe9TOOSFL4ZCQelgW6KFY',
    appId: '1:356796506211:web:34d510ea2f7a739a06d856',
    messagingSenderId: '356796506211',
    projectId: 'swinghop',
    authDomain: 'swinghop.firebaseapp.com',
    storageBucket: 'swinghop.firebasestorage.app',
    measurementId: 'G-RGTB7RCVFE',
  );
}
